name: Telegram Alerts

on:
  schedule:
    - cron: "*/5 * * * *"   # هر 5 دقیقه
  workflow_dispatch:        # اجرا با دکمه Run هم می‌شود

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas numpy requests
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SYMBOL:  ${{ vars.SYMBOL }}
          TIMEFRAME: ${{ vars.TIMEFRAME }}
          EQUITY:  ${{ vars.EQUITY }}
          RISK:    ${{ vars.RISK }}
          MAX_LEV: ${{ vars.MAX_LEV }}
        run: python main.py
