name: Telegram Alerts

on:
  schedule:
    - cron: "*/5 * * * *"   # هر 5 دقیقه
  workflow_dispatch:        # اجرای دستی

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy ccxt

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SYMBOL: ${{ vars.SYMBOL }}
          TIMEFRAME: ${{ vars.TIMEFRAME }}
          EQUITY: ${{ vars.EQUITY }}
          RISK: ${{ vars.RISK }}
          MAX_LEV: ${{ vars.MAX_LEV }}
          EXCHANGES: ${{ vars.EXCHANGES }}
        run: python main.py
